export const ExchangeTypes = {
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_CURRENCIES_SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
  FETCH_LIVE_EXCHANGE: 'FETCH_LIVE_EXCHANGE',
  FETCH_LIVE_EXCHANGE_SUCCESS: 'FETCH_LIVE_EXCHANGE_SUCCESS',
  CONVERT: 'CONVERT',
  CONVERT_INTERNAL: 'CONVERT_INTERNAL',
  CONVERT_SUCCESS: 'CONVERT_SUCCESS',
  EXCHANGE_LOADING: 'EXCHANGE_LOADING',
  EXCHANGE_LOADED: 'EXCHANGE_LOADED'
}